default: &default
      adapter: postgresql
      encoding: unicode
      pool: 5
      username: <%= ENV['USERNAME'] %>
      password: <%= ENV['PASSWORD'] %>
      host:     <%= ENV['IP'] %>
      timeout: 20000

development:
  <<: *default
  database: phones_development

test:
  <<: *default
  database: phones_test
  
production:
  <<: *default
  database: phones_development